version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pesquisa-gapol
    container_name: pesquisa-gapol
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: pesquisa-gapol-db
    ports:
      - "3338:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - ./database/data.sql:/data/data.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
